#pragma once

#include <fstream>

void WriteFileHeader(std::fstream& file)
{
    if (file.is_open())
    {
        file << "// THIS FILE IS AUTO GENERATED BY THE INSIGHT REFLECT TOOL. ANY MODIFICATIONS WILL BE OVERWRITTEN." << "\n";
        file << "#pragma once" << "\n" << "\n";
    }
}