#include "Utils.h"

#include <filesystem>

namespace InsightReflectTool
{
    namespace Utils
    {
        void WriteGeneratedFileHeader(std::fstream& file)
        {
            if (file.is_open())
            {
                file << "// THIS FILE IS AUTO GENERATED BY THE INSIGHT REFLECT TOOL. ANY MODIFICATIONS WILL BE OVERWRITTEN." << "\n";
                file << "#pragma once" << "\n" << "\n";
            }
        }

        void ValidateOutputPath(std::string_view path)
        {
            std::string folderPath = std::filesystem::path(path).parent_path().string();
            if (!std::filesystem::exists(folderPath))
            {
                std::filesystem::create_directory(folderPath);
            }
        }
    }
}